const { boot, quickGame } = require('./harness');
const fpFinish = (x) => { x.click('[data-act="fpScore"][data-to="0"][data-score="4"]'); x.click('[data-act="fpScore"][data-to="1"][data-score="5"]'); x.slide('[data-slide="finish"]'); return x; };
const app = quickGame(boot());
console.log('after start', app.dump());
app.advance(90000);
app.click('[data-act="touchdown"][data-team="1"]');
console.log('conv modal:', app.modal());
app.slide('[data-slide="conv"][data-pts="2"]');
console.log('scores', app.scores(), 'clock', app.clock());
app.advance(20 * 60000 + 500);
console.log('after half expiry', app.dump());
app.slide('[data-slide="startHalf2"]');
app.advance(19 * 60000 + 30000);
console.log('2H 0:30', app.dump());
app.advance(60000);
console.log('after game over', app.dump());
fpFinish(app);
console.log('after finish', app.screen(), app.state().games.length, app.text('#gamelist').slice(0, 120));
const app2 = app.relaunch();
console.log('relaunched', app2.screen(), app2.state().games.length);
console.log('errors', app.errors(), app2.errors());
